### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/sds-replicated-volume#170]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update registry.deckhouse.io/base_images/golang Docker tag to v1.22.6](../pull/169)

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>images/drbd-reactor/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-affinity-controller/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-csi/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.21.6-bullseye@sha256:a363973b58d4d5a91d6e8f700c847e87c1143459e55464fefca9e6135358af98`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-drbd-wait/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-scheduler-admission/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-scheduler-extender/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-server/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`
 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/linstor-wait-until/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

<details><summary>images/spaas/Dockerfile</summary>

 - `registry.deckhouse.io/base_images/golang 1.19.3-bullseye@sha256:3d68e9eabd09f01f5851297902f2756ee2456a2e28b212e553315a3ddfcffe4b`
 - `registry.deckhouse.io/base_images/ubuntu jammy-20221130@sha256:c14c3b1242536729ce5227ff833144977b4e378723858fb73a4cf40ea6daaf6a`

</details>

</blockquote>
</details>

**Comment by duckhawk** [comment]
Fixed
